# Generated by Django 4.1.5 on 2023-02-26 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='usename',
            new_name='username',
        ),
    ]
