# Generated by Django 4.1.5 on 2023-03-03 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classapp', '0004_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('class_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
