# Generated by Django 4.1.5 on 2023-03-03 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classapp', '0005_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=50)),
                ('room', models.CharField(max_length=20)),
                ('subject_name', models.TextField()),
                ('join_code', models.CharField(max_length=7)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classapp.classroom')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classapp.classroom')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classapp.user')),
            ],
        ),
        migrations.DeleteModel(
            name='Class',
        ),
    ]
