# Generated by Django 4.1.5 on 2023-03-03 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classapp', '0006_classroom_student_teacher_delete_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='section',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
