# Generated by Django 4.1.5 on 2023-03-03 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classapp', '0007_classroom_section'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classroom',
            old_name='username',
            new_name='owner',
        ),
        migrations.AlterModelTable(
            name='classroom',
            table='classapp_classroom',
        ),
    ]
