# Generated by Django 4.1.5 on 2023-03-14 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classapp', '0011_topic_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
