# Generated by Django 4.1.5 on 2023-03-28 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classapp', '0012_assignment_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='files',
            field=models.FileField(default='empty.txt', upload_to='documents/'),
        ),
    ]
