# Generated by Django 4.1.5 on 2023-03-29 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classapp', '0014_remove_assignment_files_remove_topic_classroom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='files',
            field=models.FileField(default='empty.txt', upload_to='media/'),
        ),
    ]
