# Generated by Django 4.1.5 on 2023-03-29 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classapp', '0015_alter_topic_files'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='assignment',
            table='classapp_assignment',
        ),
        migrations.AlterModelTable(
            name='student',
            table='classapp_student',
        ),
        migrations.AlterModelTable(
            name='teacher',
            table='classapp_teacher',
        ),
        migrations.AlterModelTable(
            name='topic',
            table='classapp_topic',
        ),
    ]
