# Generated by Django 4.1.5 on 2023-03-30 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classapp', '0016_alter_assignment_table_alter_student_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='media/submissions')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classapp.assignment')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classapp.user')),
            ],
        ),
    ]
