# Generated by Django 4.1.5 on 2023-03-30 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classapp', '0017_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='file',
            field=models.FileField(null=True, upload_to='submissions/'),
        ),
        migrations.AlterModelTable(
            name='submission',
            table='classapp_submission',
        ),
    ]
