# Generated by Django 4.1.5 on 2023-03-31 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classapp', '0018_alter_submission_file_alter_submission_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='submission_time',
            field=models.DateTimeField(null=True),
        ),
    ]
